In [12]:
import numpy as np






patient_profiles = np.loadtxt(
    "patient_profiles.csv",
    delimiter=",",
    skiprows=1
)

patient_profiles=patient_profiles[:,1:5]

comparisions=np.loadtxt(
    "pairwise_comparisons.csv",
    delimiter=",",
    skiprows=1,
    dtype=str,
    usecols=(0,1,5)
)


comparisions[:, 0] = [
    int(x[1:]) - 1
    for x in comparisions[:, 0]
]
comparisions[:, 1] = [
    int(x[1:]) - 1
    for x in comparisions[:, 1]
]

# Convert everything to float/int
comparisions = comparisions.astype(float)

n = comparisions.shape[0]

data = np.zeros((n, 9))

for i in range(n):
    p1 = int(comparisions[i, 0])
    p2 = int(comparisions[i, 1])

    x = np.concatenate((
        patient_profiles[p1, :],
        patient_profiles[p2, :]
    ))

    # Add label
    diff = np.append(x, comparisions[i, 2])

    data[i, :] = diff

print(data)


[[ 4.  0. -1. ...  3.  0.  0.]
 [ 0.  2.  3. ... -1.  2.  1.]
 [ 0.  2.  3. ...  1.  2.  1.]
 ...
 [ 4.  0.  3. ...  3.  2.  1.]
 [ 4.  0.  3. ...  1.  0.  1.]
 [ 4.  0.  3. ...  2.  1.  0.]]


4 parameters of A and 4 of B and then result.

In [5]:
X=data[:,0:8]
y=data[:,8]
print(X)
print(y)

[[ 4.  0. -1. ...  2.  3.  0.]
 [ 0.  2.  3. ...  0. -1.  2.]
 [ 0.  2.  3. ...  0.  1.  2.]
 ...
 [ 4.  0.  3. ...  0.  3.  2.]
 [ 4.  0.  3. ...  2.  1.  0.]
 [ 4.  0.  3. ...  2.  2.  1.]]
[0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1.
 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 1. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 0. 0. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 0. 1. 1. 0. 1. 1. 1. 1. 0. 0. 1. 1. 0. 1. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 1. 1.
 1. 1. 0. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 0. 1. 0. 0. 1. 0. 0. 1. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 1. 0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 0.
 1. 1. 0. 1. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 1. 1. 1. 0. 1. 1.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.
 1. 1. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 0. 0. 0. 0. 0. 1.
 1. 1

In [8]:
from sklearn.linear_model import LogisticRegression

# Create model
model = LogisticRegression()

# Train
model.fit(X, y)

# Predict all labels (0 or 1)
y_pred = model.predict(X)

print(y_pred)

[0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 1. 0. 0. 1. 1. 1. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 0. 0. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 0. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 0. 1. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 1. 1. 1.
 1. 1. 0. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 0. 1. 0. 0. 1. 0. 0. 1. 0. 1. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 1. 0. 0. 0. 0. 0. 1. 1. 1.
 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0.
 1. 1. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0.
 1. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 1. 1. 1. 1. 1.
 0. 1. 0. 1. 1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.
 0. 0. 0. 1. 0. 1. 1. 1. 0. 0. 1. 0. 1. 1. 1. 0. 1.

In [9]:
error_percent = np.mean(y_pred != y) * 100

print("Error %:", error_percent)

Error %: 13.846153846153847
