In [37]:
import numpy as np






patient_profiles = np.loadtxt(
    "patient_profiles.csv",
    delimiter=",",
    skiprows=1
)

patient_profiles=patient_profiles[:,1:5]

comparisions=np.loadtxt(
    "pairwise_comparisons.csv",
    delimiter=",",
    skiprows=1,
    dtype=str,
    usecols=(0,1,5)
)


comparisions[:, 0] = [
    int(x[1:]) - 1
    for x in comparisions[:, 0]
]
comparisions[:, 1] = [
    int(x[1:]) - 1
    for x in comparisions[:, 1]
]

# Convert everything to float/int
comparisions = comparisions.astype(float)


n = comparisions.shape[0]
data = np.zeros((n, 5))

for i in range(n):
    p1 = int(comparisions[i, 0])
    p2 = int(comparisions[i, 1])

    diff = patient_profiles[p1, :] - patient_profiles[p2, :]

    # Add comparison result at the end
    diff = np.append(diff, comparisions[i, 2])

    data[i, :] = diff

print(data)








[[ 4. -2. -4.  2.  0.]
 [-4.  2.  4. -2.  1.]
 [-4.  2.  2. -2.  1.]
 ...
 [ 0.  0.  0. -2.  1.]
 [ 4. -2.  2.  0.  1.]
 [ 4. -2.  1. -1.  0.]]


first 4 are differences in parameters and last one is result.

In [38]:
X=data[:,0:4]
y=data[:,4]
print(X)
print(y)

[[ 4. -2. -4.  2.]
 [-4.  2.  4. -2.]
 [-4.  2.  2. -2.]
 ...
 [ 0.  0.  0. -2.]
 [ 4. -2.  2.  0.]
 [ 4. -2.  1. -1.]]
[0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1.
 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 1. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 0. 0. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 0. 1. 1. 0. 1. 1. 1. 1. 0. 0. 1. 1. 0. 1. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 1. 1.
 1. 1. 0. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 0. 1. 0. 0. 1. 0. 0. 1. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 1. 0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 0.
 1. 1. 0. 1. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 1. 1. 1. 0. 1. 1.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.
 1. 1. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 0. 0. 0. 0. 0. 1.
 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0. 1. 0. 1. 1. 1.
 0. 

In [41]:
from sklearn.linear_model import LogisticRegression

# Create model
model = LogisticRegression()

# Train
model.fit(X, y)

# Predict all labels (0 or 1)
y_pred = model.predict(X)

print(y_pred)

[0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 1. 0. 0. 1. 1. 1. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 0. 0. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 0. 1. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 1. 1. 1.
 1. 1. 0. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 0. 1. 0. 0. 1. 0. 0. 1. 0. 1. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0.
 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1.
 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0.
 1. 1. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0.
 1. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 1. 1. 1. 0. 1.
 0. 1. 0. 1. 1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.
 0. 0. 0. 1. 0. 1. 1. 1. 0. 0. 1. 0. 1. 1. 1. 0. 1.

Applied logistic regression on differences.


In [42]:
error_percent = np.mean(y_pred != y) * 100

print("Error %:", error_percent)

Error %: 13.675213675213676
